# Plugins
gems:
- jekyll-sitemap
safe: false

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']


# Site Settings
title: "GBG BizFest "
email: ""
description: "GBG BizFest"
baseurl: ""
url: "http://www.bizfest.cz"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-76054163-1"
googleAnalyticsSiteUrl: "www.bizfest.cz"
siteVerification: ""

# Organizer Info
organizerName: "GBG Prague"
organizerAlternateName: "Google Business Group Prague"
organizerDescription: ""
organizerEmail: ""
organizerLogo: "/img/seo/organizer-logo.png"
organizerLink: ""

# Head
metaKeywords: "event, gbg, bizfest, google, business, , workshop, android, chrome, prague"
twitterAccount: "@BizFest"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

# Documents
c4pUrl: "http://goo.gl/forms/2Y533qzprY486Xz22"
c4sponsorsUrl: "https://goo.gl/IhR6nU"


# Navigation
navigationLinks:
 - {permalink: "/", text: "BizFest"}
 #- {permalink: "/blog/", text: "Blog"}
 - {permalink: "/schedule/", text: "Program"}
 - {permalink: "/speakers/", text: "Řečníci"}
 - {permalink: "/team/", text: "Tým"}
bottomNavigationLinks:
 - {link: "http://goo.gl/forms/2Y533qzprY486Xz22", text: "Chci přednášet"}
rightNavigationButtons:
 - {link: "http://goo.gl/forms/2Y533qzprY486Xz22", text: "Chci přednášet"}

# Hero Block
heroImage: "hero.png"
heroTitle: "GBG BizFest <typeout> 2016"
heroPerex: "Vidím město veliké, jehož sláva hvězd se dotýká."
eventDate: "11. června, 2016"
typeoutTextValues: '"", "Season", "Prague", "Czech Republic"'
typeoutFallback: "Season"
heroButtons:
 - {link: "http://goo.gl/forms/2Y533qzprY486Xz22", text: "Chci přednášet"}
 - {link: "http://goo.gl/forms/aiUAFct4HFv5tjVy1", text: "Chci se registrovat"}

# About Block
aboutTitle: "O BizFestu"
aboutBlock:
 - {title: "Conference", image: "conference.jpg", text: "The biggest Google related event in the country carefully crafted for you by GDG community! Awesome speakers and lots of fun!" }
 - {title: "Workshops", image: "workshop.jpg", text: "Full-day of workshops, hands-on experience, hacking and debugging. Come and tame your favourite technology!" }
 - {title: "Hackathon", image: "hackathon.jpg", text: "Full-day freestyle hackathon! Want some real team building on friday? Grab your team and join our hackathon!" }

aboutTitle2: "O BizFestu"
aboutBlock2:
 - {text: "Zaměřeno na růst, podpořeno technologiemi. </br>Festival od lidí z byznysu pro lidi z byznysu. </br>Maximum workshopů a minimum teorie." }

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "150", specialCharacter: "+", info: "účastníků", detail: "z malých a středních firem"}
 - {count: "15", specialCharacter: "+", info: "workshopů", detail: "na jednom místě"}
 - {count: "3", specialCharacter: "", info: "paralelní programy", detail: "networking a odpočinková zóna"}

# Latest News Block
latestNewsTitle: "Novinky"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Venue"
eventLocationName: "Impact Hub Praha"
eventLocationLink: "http://www.hubpraha.cz/"
eventStreetAddress: "Drtinova 557/10"
eventAddressLocality: "Praha"
eventAddressLocalityRegion: "Praha 5-Smíchov"
eventPostalCode: "15000"
eventAddressCountry: "Česká Republika"
eventStartTime: "2016-06-11T09:00"
eventDoorTime: "09:00"
eventEndTime: "2016-06-11T18:00"
eventPlaceCoordinates: "50.076465, 14.402273"
mapCenterCoordinates: "50.076465, 14.402273"
mapMobileCenterCoordinates: "50.076465, 14.402273"

# Venue Block
venueBlockTitle: "Venue"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Impact Hub Praha"
venueFeatures: ["Inspirativní prostor pro setkávání", "Meeting rooms", "Chill out zóna"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"

# Partners Block
organizersTitle: "Organizátoři"
partnersTitle: "Partneři"
partnersC4sponsorsButton: "Staň se partnerem"

# Subscribe Block
subscribeImage: "subscribe.jpg"
subscribeTitle: "Subscribe for updates"
subscribeAction: "https://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Tickets Block
ticketsTitle: "Vstupenka"
ticketsInfo: "První ročník Bizfestu bude zdarma, ale v případě vaší spokojenosti je možnost dobrovolného příspěvku ve výši 199 Kč splatného na místě."
ticketsOffers:
 -
  name: "Nultý ročník"
  price: "199"
  priceCurrency: "CZK"
  voluntarily: true
  voluntarilyText: "Dobrovolné vstupné"
  ticketsNumber: "150"
  featured: true
  buyButtonLink: "http://goo.gl/forms/aiUAFct4HFv5tjVy1"
  buyButtonText: "Chci se registrovat"
  ticketContentList: ["Přednášky, Workshopy, Technologie", "Inovace, Management, Marketing", "Networking"]
  validFrom: "2016-06-11T09:00"
  validThrough: "2016-06-11T18:00"
 

# Footer
socialLinks:
 - {link: "https://plus.google.com/117705251838796315106/posts", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=gbgprague", icon: "twitter"}
 - {link: "https://www.facebook.com/gbgprague/", icon: "facebook"}
footerBlocks:
 -
  title: "Odkazy"
  links:
   - {link: "http://www.gug.cz/cs/gbg/skupiny/prague", text: "GBG Prague"}
 -
  title: "Kontakty"
  links:
   - {link: "mailto:gbgprague@gug.cz", text: "gbgprague@gug.cz"}

# Blog
blogTitle: "Latest news"
blogCommentsEnabled: true
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: "O nás"
aboutUs: "Jsme parta early adopterů, inovátorů kolem internetu, technologií a jsme sdruženi v google user group ČR, kde pro uživatele, lidi z vývoje, byznysu i vzdělávání organizujeme akce různých formátů. Po organizaci loňského Devfestu jsme se rozhodli uspořádat festival byznys charakteru, kde se zaměříme na růst firem podpořen moderními technologiemi."

