# Plugins
gems:
- jekyll-sitemap
safe: true

# Build Settings
markdown: kramdown
permalink: pretty
exclude: ['/automation/', 'README.md', 'LICENSE.txt', 'CNAME']

# Site Settings
title: "GEGFest Praha 2018"
email: "gegfest@gegcr.cz"
description: "GEG GEGFest"
baseurl: ""
url: "http://www.gegfest.cz"
permalink: "/blog/:title"
googleAnalyticsTrackingId: "UA-61667272-1"
googleAnalyticsSiteUrl: "www.gegfest.cz"
siteVerification: "gLYI7PR32KLJJrfj32ML8nvgZ9N85pvdp15VJU6PGFc"

#DOPLNIT EMAIL
#DOPLNIT DESCRIPTION

# Organizer Info
organizerName: "GEG ČR"
organizerAlternateName: "Google EDU Group Česká republika"
organizerDescription: ""
organizerEmail: "gegfest@gegcr.cz"
organizerLogo: "/img/seo/organizer-logo.gif"
organizerLink: "http://www.gegcr.cz/"


# Head
metaKeywords: "event, geg, gegfest, google, education, učitelé, vzdělávání, technologie"
twitterAccount: "@GEGCR"
socialImageSrcGooglePlus: "/img/seo/sharing-google-plus.png"
socialImageSrcTwitter: "/img/seo/sharing-twitter.png"
socialImageSrcFacebook: "/img/seo/sharing-facebook.png"

#DOPLNIT, UPRAVIT DOKUMENT PRO PARTNERY POKUD BUDE POTREBA
# Documents
c4pUrl: "http://bit.ly/dfua-c4p"
c4sponsorsUrl: "/assets/GDG_DevFest_Partnership.pdf"


# Navigation
navigationLinks:
 - {permalink: "/", text: "GEGFest"}
 - {permalink: "/blog/", text: "Novinky"}
 - {permalink: "/tym/", text: "Tým"}
bottomNavigationLinks:
 - {link: "https://goo.gl/forms/tzZdXTN13C0zcedJ2", text: "Registrujte se"}
rightNavigationButtons:
 - {link: "https://goo.gl/forms/tzZdXTN13C0zcedJ2", text: "Registrujte se"}

# Hero Block
heroImage: "hero.png"
heroTitle: "GEGfest <typeout> 2018"
eventDate: "12. května 2018"
typeoutTextValues: '"Praha", "Česká republika"'
typeoutFallback: "Praha"
heroButtons:

 #- {link: "http://bit.ly/dfua-c4p", text: "Become a speaker"}
 #- {permalink: "/#tickets", text: "Buy tickets"}

 #- {link: "https://bit.ly/dfua-c4p", text: "Become a speaker"}
 - {link: "https://goo.gl/forms/tzZdXTN13C0zcedJ2", text: "Registrujte se"}

# About Block
aboutTitle: "O GEGfestu"
aboutBlock:
 - {title: "Konference", image: "conference.png", text: "<strong>Největší konference o technologiích Google ve vzdělávání v České republice.</strong> Program nabitý praktickými zkušenostmi, metodikou a hlavně nekonečnou inspirací, jak zefektivnit a inovovat výuku. Konference učitelů (nejen) pro učitele, pro které jsou moderní technologie výzvou, ale i cestou k obohacení výuky.</br>Vstup je vždy zdarma, registrace je však nezbytná." }
 - {title: "Přednášky", image: "presentation.png", text: "Dopolední program naplní několik přednášek s tématy z různých oblastí okolo technologií, vzdělávání a moderních trendů ve výuce. Pozvali jsme velmi zajímavé hosty, od kterých lze vždycky očekávat pěknou dávku inspirace. Těšíme se na ně!" }
 - {title: "Workshopy", image: "workshop.png", text: "V odpoledním programu se nabízí prostor přímo pro vás. Z nabídky workshopů si budete moci poskládat své vlastní odpoledne. </br> Workshopy povedou učitelé z praxe, kteří se rádi podělí o své zkušenosti a dovednosti právě s vámi. Uvidíte nejrůznější aplikace a technologie v rukách učitelů, kteří s nimi umějí a navíc je to baví. " }
 

# Statistic Block
statisticBlockImage: "statistic.jpg"
statisticBlock:
 - {count: "250", specialCharacter: "", info: "účastníků", detail: ""}
 - {count: "1", specialCharacter: "", info: "den", detail: ""}
 - {count: "27", specialCharacter: "", info: "workshopů", detail: ""}


# About Block
aboutTitle2: "Google EDU Group ČR"
aboutBlock2:
 - {title2: "GEG ČR", text2: "Google EDU Group ČR je otevřená komunita učitelů se zájmem o technologie.</br> Pomáháme ostatním učitelům i sobě navzájem lépe, tvořivě a s radostí využívat (nejen) Google technologie ve škole.</br>  Podporujeme setkávání učitelů, vzájemné učení se, sdílení zkušeností, nápadů a inspirací.</br> Vytváříme síť GEG skupin, které pořádají vzdělávací a komunitní akce pro učitele z okolí nebo online formou webinářů.</br><strong>O našich akcích se více dozvíte na <a href='http://www.gegcr.cz' target='_blank'>www.gegcr.cz</a>.</strong>" }

#TAHLE SEKCE ASI PRYC
# Latest News Block
latestNewsTitle: "Novinky"

# Rockstar Speakers Block
rockstarSpeakersImage: "rockstar-speakers.jpg"
rockstarSpeakersCount: 4
rockstarSpeakersTitle: "Rockstar speakers"
rockstarSpeakersButtonText: "See all speakers"

# Location Block
locationBlockTitle: "Umístění"
eventLocationName: "Univerzita Karlova v Praze Pedagogická fakulta"
eventLocationLink: ""
eventStreetAddress: "Magdalény Rettigové 4"
eventAddressLocality: "Praha 1"
eventAddressLocalityRegion: ""
eventPostalCode: "11639"
eventAddressCountry: "Czech Republic"
eventStartTime: "2017-05-13T9:00"
eventDoorTime: "09:00"
eventEndTime: "2017-05-13T20:00"
eventPlaceCoordinates: "50.079821, 14.420678"
mapCenterCoordinates: "50.079821, 14.420678"
mapMobileCenterCoordinates: "50.079821, 14.420678"

# Venue Block
venueBlockTitle: "Místo"
venueBigImage: "venue_0.jpg"
venueSmallImage1: "venue_1.jpg"
venueSmallImage2: "venue_2.jpg"
venueSmallImage3: "venue_3.jpg"
venueTitle: "Univerzita Karlova v Praze Pedagogická fakulta"
venueFeatures: ["Přednáškové místnosti", "Místo na workshopy"]

# Tweets Feed Block
tweetsFeedImage: "twitter-feed.jpg"
tweetsFeedTitle: "What's Up?"
twitterHashTag: "devfest"
twitterFeed: "http://lviv.gdg.org.ua/tweetledee/favoritesjson.php?c=10&cache_interval=8000"



# Subscribe Block
#subscribeImage: "subscribe.jpg"
#subscribeTitle: "Subscribe for updates"
#subscribeAction: "http://gdg.us5.list-manage1.com/subscribe/post?u=9fc8aa205b0521b5f05fc8e1e&amp;id=ae0fb459fc"
#subscribeInfo: "Registration will be open around end of August. Number of tickets are limited. Stay tuned!"

# Partners Block
organizersTitle: "Organizuje"
partnersTitle: "Partneři"
partnersC4sponsorsButton: "Staň se partnerem"


# Tickets Block
ticketsTitle: "Pricetable"
ticketsInfo: "Tickets grant access to all conference sections, coffee brakes, lunch and party. Accommodation is NOT included in the ticket price."
ticketsOffers:
 -
  name: "Early Bird"
  price: "350"
  priceCurrency: "UAH"
  ticketsNumber: "150"
  ribbon: "-5%"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-25T10:00"
  validThrough: "2014-09-30T23:59"
 -
  name: "Last Chance"
  price: "450"
  priceCurrency: "UAH"
  ticketsNumber: "100"
  ribbon: "-20%"
  featured: true
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-10-01T00:00"
  validThrough: "2014-10-23T23:59"
  disabled: true
 -
  name: "Student"
  price: "200"
  priceCurrency: "UAH"
  ticketsNumber: "50"
  buyButtonLink: "http://dfua.ticketforevent.com/"
  buyButtonText: "Buy Now"
  additionalInfo: "Requires a valid student ID at the conference check in. Without student ID at the check in, ticket will be cancelled without refund"
  ticketContentList: ["Lorem ipsum is simply", "Dummy text of the printing", "Typesetting industry"]
  validFrom: "2014-08-20T10:00"
  validThrough: "2014-10-23T23:59"
  soldOut: true
  soldOutText: "Sold Out"


# Footer
socialLinks:
 - {link: "https://plus.google.com/+gegcrcz/posts", icon: "google-plus"}
 - {link: "https://twitter.com/intent/user?screen_name=GEGCR", icon: "twitter"}
 - {link: "http://www.facebook.com/gegcr", icon: "facebook"}
 - {link: "https://www.youtube.com/user/gegcrcz", icon: "youtube"}

footerBlocks:
 -
  title: "Odkazy"
  links:
   - {link: "http://www.gegcr.cz/", text: "GEG ČR"}
   - {link: "http://www.praha2016.gegfest.cz", text: "GEGfest 2016"}
   - {link: "http://www.virtualni-prohlidky360.cz/projekty/PFUKPraha/_flash/VirtualTour_PFUKPraha.html", text: "Virtuální prohlídka Venue PedF UK"}
   - {link: "https://drive.google.com/drive/folders/0B6Iazp_sUPbEX01xR2toaURLMTg?usp=sharing", text: "Materiály z workshopů"}



 -
  title: "Kontakty"
  links:
   - {link: "mailto:gegfest@gegcr.cz", text: "gegfest@gegcr.cz"}


# Blog
blogTitle: "Novinky"
blogCommentsEnabled: false
discusShortName: "devfestua"

# Speakers List Block
showSessions: true

# Team Block
teamBlockTitle: ""
aboutUs: ""

