runtime: python27
api_version: 1
threadsafe: true

handlers:
- url: /tym/
  static_files: tym/index.html
  upload: index\.html$

- url: /speakers/
  static_files: speakers/index.html
  upload: index\.html$

- url: /women-techmakers/
  static_files: women-techmakers/index.html
  upload: index\.html$

- url: /businessbuild/
  static_files: businessbuild/index.html
  upload: index\.html$

- url: /geekfun/
  static_files: geekfun/index.html
  upload: index\.html$

- url: /logistics/
  static_files: logistics/index.html
  upload: index\.html$

- url: /schedule/
  static_files: schedule/index.html
  upload: index\.html$

- url: /blog/
  static_files: blog/index.html
  upload: index\.html$

- url: /blog/soutez
  static_files: blog/soutez.html
  upload: soutez\.html$

- url: /blog/novinky-test
  static_files: blog/novinky-test.html
  upload: novinky-test\.html$

- url: /blog/odpoledni-program-kopie
  static_files: blog/odpoledni-program-kopie.html
  upload: odpoledni-program-kopie\.html$

- url: /blog/prednasky
  static_files: blog/prednasky.html
  upload: prednasky\.html$

- url: /blog/workshopy
  static_files: blog/workshopy.html
  upload: workshopy\.html$

- url: /blog/prednasky-cool
  static_files: blog/prednasky-cool.html
  upload: prednasky-cool\.html$

- url: /blog/registrace
  static_files: blog/registrace.html
  upload: registrace\.html$

- url: /blog/khan-a-wiki
  static_files: blog/khan-a-wiki.html
  upload: khan-a-wiki\.html$

- url: /blog/novy-gegfest2018
  static_files: blog/novy-gegfest2018.html
  upload: novy-gegfest2018\.html$

- url: /blog/3Dtisk
  static_files: blog/3Dtisk.html
  upload: 3Dtisk\.html$

- url: /blog/copywriting
  static_files: blog/copywriting.html
  upload: copywriting\.html$

- url: /blog/ohlednuti
  static_files: blog/ohlednuti.html
  upload: ohlednuti\.html$

- url: /blog/pravidla
  static_files: blog/pravidla.html
  upload: pravidla\.html$

- url: /blog/velky-klaun
  static_files: blog/velky-klaun.html
  upload: velky-klaun\.html$

- url: /blog/omluva
  static_files: blog/omluva.html
  upload: omluva\.html$

- url: /blog/wikipedie
  static_files: blog/wikipedie.html
  upload: wikipedie\.html$

- url: /blog/khanova-skola
  static_files: blog/khanova-skola.html
  upload: khanova-skola\.html$

- url: /
  static_files: index.html
  upload: index\.html$

- url: /cod/
  static_files: cod/index.html
  upload: index\.html$

- url: /assets/(.*)
  static_files: assets/(.*)
  upload: index\.html$

- url: /js/(.*)
  static_files: js/\1
  upload : js/.*
  expiration: "90d"

- url: /(.*\.(gif|png|jpg))$
  static_files: \1
  upload: .*\.(gif|png|jpg)$
  expiration: "90d"

- url: /(.*)$
  static_files: \1
  upload: .*$
  expiration: "30m"